/*

  The hiha programming language

  Copyright © 2026 Barry Schwartz

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.

*/

#include <config.h>
#include <limits.h>
#include <error.h>
#include <exitfail.h>
#include <libhiha/str_nul.h>
#include <libhiha/spookyhash.h>

#define _(msgid) HIHA_GETTEXT (msgid)

struct str_nul_hash_context
{
  const char *s;
  size_t n;
  uint64_t *hashes;             /* Memoized hashes. */
  size_t num_hashes;
};

static const uint64_t str_nul_hash_this_first[2] = {
  /*
     A 128-bit, cryptographically sound random number, generated by the
     following command:

     head -c 16 /dev/urandom | xxd -p

   */
  [0] = 0x8abcd693d450866a,
  [1] = 0x5a4e3670ab79b8a0
};

static const uint64_t str_nul_hash_for_NULL_string[2] = {
  /*
     A 128-bit, cryptographically sound random number, generated by the
     following command:

     head -c 16 /dev/urandom | xxd -p

   */
  [0] = 0xe30ac2a24e3d30e4,
  [1] = 0x30d3f7e22c740d18
};

HIHA_VISIBLE str_nul_hash_context_t
str_nul_hash_init (const char *s)
{
  str_nul_hash_context_t context =
    XMALLOC (struct str_nul_hash_context);
  context->s = s;
  context->n = (s != NULL) ? strlen (s) : 0;
  context->hashes = NULL;
  context->num_hashes = 0;
  return context;
}

static inline void
check_str_nul_hash_index (unsigned int i)
{
  /* Put this here to make the program “terminating in principle” when
     things like ideal hashmaps do the practically impossible. */
  if (i == ((unsigned int) INT_MAX) + 1)
    {
      error (exit_failure, 0,
             "str_nul_hash index out of bounds: %u", i);
      abort ();
    }
}

static void
copy_old_str_nul_hashes (uint64_t *new_hashes,
                         str_nul_hash_context_t context)
{
  if (context->hashes != NULL)
    memcpy (new_hashes, context->hashes,
            context->num_hashes * sizeof (uint64_t));
}

static void
compute_new_str_nul_hashes (uint64_t *new_hashes,
                            size_t new_num_hashes,
                            str_nul_hash_context_t context)
{
  /* Memoize all the hashes up to new_num_hashes.

     Memoizing all the hashes (rather than doing anything more
     complicated) presumes algorithms will go progressively from hash
     0, to hash 1, to hash 2, and so on. Thus, in practice, there will
     be no hashes computed and simply thrown away. */

  spookyhash_context_t boo;

  for (size_t i = context->num_hashes; i != new_num_hashes; i += 2)
    {
      uint64_t seed1 = i / 2;
      uint64_t seed2 = seed1;
      spookyhash_init (&boo, seed1, seed2);
      if (context->s != NULL)
        {
          spookyhash_update (&boo, str_nul_hash_this_first,
                             2 * sizeof (uint64_t));
          spookyhash_update (&boo, context->s,
                             context->n * sizeof (char));
        }
      else
        spookyhash_update (&boo, str_nul_hash_for_NULL_string,
                           2 * sizeof (uint64_t));
      spookyhash_final (&boo, &new_hashes[i], &new_hashes[i + 1]);
    }
}

HIHA_VISIBLE uint64_t
str_nul_hash (str_nul_hash_context_t context, unsigned int i)
{
  check_str_nul_hash_index (i);

  /* j = i rounded to the next higher even. */
  unsigned int j = ((i & ~1U) + 2);

  if (context->num_hashes < j)
    {
      uint64_t *new_hashes = XNMALLOC (j, uint64_t);
      copy_old_str_nul_hashes (new_hashes, context);
      compute_new_str_nul_hashes (new_hashes, j, context);
      context->hashes = new_hashes;
      context->num_hashes = j;
    }

  return context->hashes[i];
}

/*
  local variables:
  mode: c
  coding: utf-8
  end:
*/
